upaas:
  cauth:
    server:
      port: 8070

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 12345678
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    maxActive: 50
    initialSize: 1
    maxWait: 60000
    minIdle: 1
