server:
  port: 8888

spring:
  profiles: dev
  application:
    name: upaas-config-server
  cloud:
    config:
      server:
        git:
          uri: file://data/thgy/github/Ulord-platform/upaas/config-repo

logging:
  config: classpath:log4j2.xml

eureka:
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
# Test environment

server:
  port: 8888

spring:
  profiles: test
  application:
    name: upaas-config-server
  cloud:
    config:
      server:
        git:
          uri: file:///data/config-repo
logging:
  config: classpath:log4j2.xml

eureka:
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
# Production environment
server:
  port: 8888

spring:
  profiles: prod
  application:
    name: upaas-config-server
  cloud:
    config:
      server:
        git:
          uri: file://data/upaas/config-repo
logging:
  config: classpath:log4j2-prod.xml

eureka:
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
